name: webservices
channels:
  - conda-forge
platforms:
  - linux-64
  - linux-aarch64
dependencies:
  - anaconda-client >=1.8.0
  - cachetools
  - conda
  - conda-build
  - conda-forge-metadata >=0.9.2
  - conda-forge-pinning
  - conda-forge-tick >=2024.9.26
  - conda-forge-feedstock-ops >=0.7.0
  - conda-smithy >=3.34.1  # this pin is for jinja2 sandboxes
  - cryptography >=39
  - docker-squash
  - python-dateutil
  - git
  - gitpython
  - lxml
  - mock
  - parameterized
  - pip
  - pygithub >=2.2.0  # for GH App endpoints
  - python =3.11.*
  - pytz
  - pyyaml
  - requests
  - ruamel.yaml >=0.16
  - ruamel.yaml.jinja2
  - setuptools
  - setuptools_scm >=8
  - shellcheck
  - tini
  - tornado
  - tqdm
  # dev dependencies
  - pytest <8.2.0
