name: deploy

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: conda-forge
          heroku_email: becker.mr@gmail.com
          usedocker: true
