name: release

on:
  workflow_dispatch: null
  push:
    branches:
      - main

env:
  PY_COLORS: "1"
  IMAGE_NAME: condaforge/conda-forge-webservices

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1
        with:
          environment-file: conda-lock.yml
          environment-name: webservices
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge

      - name: compute next version
        id: version
        run: |
          echo "current version: "$(git describe --tags --abbrev=0)
          NEXT=$(python scripts/compute_next_version.py)
          echo "next version: ${NEXT}"
          echo "NEXT=${NEXT}" >> "$GITHUB_OUTPUT"

      # TODO: move webservices-dispatch-action to this repo and push via the following
      # - name: set up docker buildx
      #   uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      # - name: login to docker hub
      #   uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      #   with:
      #     username: condaforgebot
      #     password: ${{ secrets.CF_BOT_DH_PASSWORD }}

      # - name: build docker metadata
      #   id: meta
      #   uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
      #   with:
      #     images: ${{ env.IMAGE_NAME }}
      #     flavor: |
      #       latest=false
      #     tags: |
      #       type=raw,value=${{ steps.version.outputs.NEXT }}
      #       type=raw,value=latest

      # - name: build and push image
      #   uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: push README to docker hub
      #   uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
      #   env:
      #     DOCKER_USER: condaforgebot
      #     DOCKER_PASS: ${{ secrets.CF_BOT_DH_PASSWORD }}
      #   with:
      #     destination_container_repo: ${{ env.IMAGE_NAME }}:latest
      #     provider: dockerhub
      #     short_description: "conda-forge-webservices image used to power the admin webservices GitHub Actions integrations"
      #     readme_file: "Dockerfile_README.md"

      - name: tag and release
        run: |
          python scripts/release.py "${{ steps.version.outputs.NEXT }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
